### ISSUE TITLE
Misc Button

### ISSUE THREAD

**Issue by prashantbarca** [mtmr/DCSE#3]
Hi,

First of all. Brilliant initiative open sourcing it. Which allows alumni like myself to contribute. 

So basically the Misc Button doesn't have any function yet. Same with the search option.

**Comment by mtmr** [comment]
Hi. Thank you. No regular  Internet so I'll keep this short. Misc
button has been fixed.  I'll push the updates to the server in two
days.  Search will work if you press the search button instead of a
problem pressing enter key. Further t development, although happening
at a rapid pace, will not be deployed to this
Server. A backend update is pending and I took a break for summer
vacation  so will happen only after three weeks. Please report any
bugs you find.  Also note that this is just a beta.  I'll add you to
the private repo in two weeks once I shape the modern code. Thanks
much.

Muthu.

On 5/28/15, Prashant Anantharaman <notifications@github.com> wrote:
> Hi,
>
> First of all. Brilliant initiative open sourcing it. Which allows alumni
> like myself to contribute.
>
> So basically the Misc Button doesn't have any function yet. Same with the
> search option.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mtmr/DCSE/issues/3


-- 
Muthuraj Thangavel,
Mobile: 9655804033
